# Data Configuration
data:
  input_path: "data/input"
  output_path: "data/output"
  processed_path: "data/processed"
  batch_size: 32
  scisummnet_path: "data/scisummnet_release1.1__20190413"
  datasets:
    - name: "xlsum"
      source: "huggingface"
      enabled: true
      language: "english"
      dataset_name: "GEM/xlsum"
    - name: "scisummnet"
      source: "local"
      enabled: true
      file_patterns:
        xml: "{paper_id}.xml"
        summary: "{paper_id}.gold.txt"
      subdirs:
        documents: "Documents_xml"
        summaries: "summary"

# Preprocessing Configuration
preprocessing:
  min_length: 100
  max_length: 1000
  validation:
    missing_threshold: 5.0
    min_dataset_size: 10000
    min_text_length: 100
    max_text_length: 1000

# Embedding Configuration
embedding:
  model_name: "all-mpnet-base-v2"
  dimension: 768
  batch_size: 32
  max_seq_length: 512
  device: "cuda"

# Clustering Configuration
clustering:
  algorithm: "hdbscan"
  min_cluster_size: 5
  min_samples: 5
  metric: "euclidean"
  params:
    min_cluster_size: 5
    min_samples: 5
    metric: "euclidean"
  output_dir: "outputs/clusters"

# Visualization Configuration
visualization:
  enabled: true
  output_dir: "outputs/figures"

# Summarization Configuration
summarization:
  model_name: "facebook/bart-large-cnn"
  max_length: 150
  min_length: 50
  device: "cuda"
  batch_size: 8
  style_params:
    concise:
      max_length: 100
      min_length: 30
    detailed:
      max_length: 300
      min_length: 100
    technical:
      max_length: 200
      min_length: 50
  num_beams: 4
  length_penalty: 2.0
  early_stopping: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: 'logs/pipeline.log'

# Checkpoints Configuration
checkpoints:
  enabled: true
  dir: "outputs/checkpoints"
  save_frequency: 1000

# Validation Configuration
validation:
  min_text_length: 10
  max_missing_ratio: 0.05
  min_cluster_size: 5
  language: 'english'

# Metrics Configuration
metrics:
  track_embedding_quality: true
  track_cluster_stability: true
  track_summarization_quality: true