# Data Configuration
data:
  input_dir: "data/scisummnet_release1.1__20190413/top1000_complete"
  output_dir: "outputs"
  datasets:
    - name: "xlsum"
      type: "huggingface"
      path: "GEM/xlsum"
    - name: "scisummnet"
      type: "local"
      path: "data/scisummnet_release1.1__20190413"

# Preprocessing Configuration
preprocessing:
  min_length: 100
  max_length: 1000
  remove_stopwords: true
  language: "english"
  lowercase: true

# Embedding Configuration
embedding:
  model_name: "all-mpnet-base-v2"
  max_seq_length: 512
  batch_size: 32
  device: "cuda" # or "cpu" if no GPU available
  cache_dir: "models/embeddings"

# Clustering Configuration
clustering:
  algorithm: "hdbscan"
  min_cluster_size: 5  # This was missing in the original config
  min_samples: 5
  metric: "euclidean"
  cluster_selection_epsilon: 0.5
  params:
    min_cluster_size: 5
    min_samples: 5
    metric: "euclidean"
    cluster_selection_epsilon: 0.5

# Summarization Configuration
summarization:
  model_name: "facebook/bart-large-cnn"
  max_length: 150
  min_length: 50
  batch_size: 8
  device: "cuda" # or "cpu" if no GPU available
  cache_dir: "models/summarization"

# Visualization Configuration
visualization:
  plot_type: "interactive"
  dimensions: 2
  perplexity: 30
  n_iter: 1000

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "outputs/pipeline.log"

# Evaluation Configuration
evaluation:
  metrics:
    - "rouge"
    - "bleu"
    - "silhouette_score"
  rouge_types:
    - "rouge1"
    - "rouge2"
    - "rougeL"

# System Configuration
system:
  random_seed: 42
  num_workers: 4
  use_gpu: true
  debug_mode: false