# Data Configuration
data:
  input_path: "data/input"
  output_path: "data/output"
  scisummnet_path: "data/scisummnet_release1.1__20190413"
  processed_path: "data/processed"
  batch_size: 32

# Preprocessing Configuration
preprocessing:
  min_length: 100
  max_length: 1000
  validation:
    missing_threshold: 5.0
    min_dataset_size: 10000
    min_text_length: 100
    max_text_length: 1000

# Embedding Configuration
embedding:
  model_name: "all-mpnet-base-v2"
  dimension: 768
  batch_size: 32
  max_seq_length: 512
  device: "cuda"

# Clustering Configuration
clustering:
  algorithm: "hdbscan"
  min_cluster_size: 5
  min_samples: 5
  metric: "euclidean"
  params:
    min_cluster_size: 5
    min_samples: 5
    metric: "euclidean"
  output_dir: "outputs/clusters"

# Visualization Configuration
visualization:
  enabled: true
  output_dir: "outputs/figures"

# Summarization Configuration
summarization:
  model_name: "facebook/bart-large-cnn"
  max_length: 150
  min_length: 50
  batch_size: 16

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Checkpoints Configuration
checkpoints:
  dir: "outputs/checkpoints"