data:
  xlsum_dataset: "GEM/xlsum"
  scisummnet_path: "/Users/vanessa/Dropbox/synsearch/data/scisummnet_release1.1__20190413"
  processed_path: "outputs/processed"

preprocessing:
  min_text_length: 100
  max_text_length: 1000
  language: "en"
  validation:
    missing_threshold: 5.0
    min_dataset_size: 10000
    min_text_length: 100
    max_text_length: 1000

embedding:
  model_name: "sentence-transformers/all-mpnet-base-v2"
  batch_size: 32
  max_seq_length: 128
  device: null  # Will auto-detect GPU/CPU unless....look emoji
  output_dir: "outputs/embeddings"

clustering:
  method: "hdbscan"
  params:
    min_cluster_size: 5
    min_samples: 5
  output_dir: "outputs/clusters"

checkpoints:
  dir: "outputs/checkpoints"
  enabled: true
  cleanup_after_completion: false
  stages:
    data_loading:
      enabled: true
      save_intermediate: true
    embedding:
      enabled: true
      batch_size: 1000  # Save every N documents
    clustering:
      enabled: true
      save_intermediate: false
    summarization:
      enabled: true
      save_intermediate: true

personalization:
  enabled: true
  user_preferences:
    summary_style: "technical"  # [technical, concise, detailed]
    min_length: 100
    max_length: 500
  fine_tuning:
    enabled: true
    learning_rate: 1e-5
    epochs: 3
    batch_size: 8

summarization:
  model_name: "facebook/bart-large-cnn"
  max_length: 512
  min_length: 50
  batch_size: 8
  output_dir: "outputs/summaries"

visualization:
  enabled: true
  output_dir: "outputs/figures"
  umap:
    n_neighbors: 15
    min_dist: 0.1
    metric: "cosine"
    random_state: 42

evaluation:
  output_dir: "outputs/evaluation"
  metrics:
    - "rouge"
    - "clustering"
    - "silhouette"
    - "davies_bouldin"